- docs/src/utils.md
- docs/utils.md
- jvm/src/test/scala/eu/timepit/refined/StringPredicateSpecJvm.scala
- jvm/src/test/scala/eu/timepit/refined/StringUtilSpecJvm.scala
- notes/0.2.1.markdown
- shared/src/main/scala/eu/timepit/refined/string.scala
- shared/src/main/scala/eu/timepit/refined/util/string.scala
> Add XPath predicate

- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefAux.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- docs/src/type_aliases.md
- docs/type_aliases.md
- notes/0.3.2.markdown
closes #78. This commit still misses documentation. I'll add them later.
> Add RefType.applyRef

- core/shared/src/main/scala/eu/timepit/refined/internal/RefinePartiallyApplied.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
force throws an IllegalArgumentException if T is invalid according to P.
> Add force which is a partial function T => F[T, P]

- build.sbt
- project/plugin-mima.sbt
> Use MiMa to detect binary compat issues

- project/plugin-tut.sbt
Reverts fthomas/refined#118 because of https://github.com/tpolecat/tut/issues/87
> Revert "Update to tut 0.4.1"

- build.sbt
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- core/shared/src/main/scala/eu/timepit/refined/api/Validate.scala
- core/shared/src/main/scala/eu/timepit/refined/auto.scala
- core/shared/src/main/scala/eu/timepit/refined/boolean.scala
- core/shared/src/main/scala/eu/timepit/refined/collection.scala
- core/shared/src/main/scala/eu/timepit/refined/generic.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/Resources.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/InferMacro.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- core/shared/src/main/scala/eu/timepit/refined/package.scala
- core/shared/src/main/scala/eu/timepit/refined/string.scala
This contains a workaround for
https://github.com/scalastyle/scalastyle-sbt-plugin/issues/47
> Fix Scalastyle

- build.sbt
- core/jvm/src/test/scala/eu/timepit/refined/GenericValidateSpecJvm.scala
- core/jvm/src/test/scala/eu/timepit/refined/StringUtilSpecJvm.scala
- core/shared/src/test/scala/eu/timepit/refined/CollectionInferenceSpec.scala
- core/shared/src/test/scala/eu/timepit/refined/StringUtilSpec.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.3.6.markdown
This is in anticipation to the next shapeless release. It will be updated to a non-snapshot version when shapeless 2.3.0 is released. We also need to update the release notes then.
> Update to shapeless 2.3.0

- README.md
- core/shared/src/main/scala/eu/timepit/refined/collection.scala
- core/shared/src/test/scala/eu/timepit/refined/CollectionValidateSpec.scala
> Add collection predicates

- core/shared/src/main/scala-2.10/eu/timepit/refined/api/Refined.scala
> Document why Refined is not a value class for 2.10

- build.sbt
Also added testJS/testJVM & shuffled things to be more comment-out-friendly
> Add coverageOff to validate

- core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- core/shared/src/test/scala/eu/timepit/refined/NumericValidateSpec.scala
Was unclear about equals, made and unmade changes.
> Added Equal, NotEqual numeric types

- build.sbt
- project/plugin-travisci.sbt
> Use sbt-travisci

- build.sbt
- latestVersion.sbt
- project/LatestVersion.scala
This reduces the manual release steps by 1
> Update latestVersion during the release

- modules/core/shared/src/main/scala/eu/timepit/refined/types/AllTypes.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/CharTypes.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/package.scala
- notes/0.6.2.markdown
Inspired by https://github.com/julien-truffaut/Monocle/pull/446
> Add aliases for refined Char

- build.sbt
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/package.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/PackageSpec.scala
- notes/0.6.2.markdown
> Add Cogen instance for any refined type

- build.sbt
- modules/pureconfig/jvm/src/main/scala/eu/timepit/refined/pureconfig/package.scala
- modules/pureconfig/jvm/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
I was also the person who complained, https://github.com/fthomas/refined/issues/272 ;)
> Change refined-pureconfig to use pureconfig 0.7.0

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericValidateSpec.scala
> Add Modulo, Divisible, NonDivisible, Even, Odd

- build.sbt
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericInferenceSpec.scala
- modules/scalaz/jvm/src/test/scala-2.12/eu/timepit/refined/scalaz/InferJavapSpec.scala
See
* http://tpolecat.github.io/2017/04/25/scalac-flags.html
* https://github.com/scala/scala/pull/5402
* https://github.com/fthomas/refined/pull/276
> Selectively enable -Ywarn-unused options

- build.sbt
- project/plugin-wartremover.sbt
This is a cheap attempt to fix #292
> Remove WartRemover

- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
Implementation for Issue https://github.com/fthomas/refined/issues/294
> Add more port-number types

- notes/0.8.3.markdown
see https://github.com/fthomas/refined/compare/v0.8.2...master
> WIP: Changelog for 0.8.3

- build.sbt
- modules/benchmark/src/main/scala/eu/timepit/refined/benchmark/RefineMacroBenchmark.scala
- project/plugin-jmh.sbt
Fixes #163. This just contains one benchmark for now but we can add more
benchmarks as needed.
> Add benchmark module

- notes/0.8.5.markdown
In preparation for the 0.8.5 release.
The changes that will go in this release are here:
https://github.com/fthomas/refined/compare/v0.8.4...master
> Release notes for 0.8.5

- README.md
I put Besedo before Zalando not to be cheeky, but because non-alphabetical
sorting bothers me. Feel absolutely free to reorder!
> Add Besedo to the list of refined users

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/package.scala
- modules/docs/dependent_refinement.md
- modules/docs/src/dependent_refinement.md
> Don't advertise Witness as workaround for dependent refinements

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Max.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Min.scala
This is just me being very pedantic about formatting and naming
variables. I'm sorry.
> Cosmetic changes in Min/Max

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/types/char.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/time.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/CharTypesSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NumericTypesSpec.scala
- notes/0.9.0.markdown
Closes https://github.com/fthomas/refined/issues/416
> Change layout of the types package

- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/string.scala
see https://github.com/fthomas/refined/pull/415#issuecomment-369221107
> Don't depend on an implicit .toString for string concatenation

- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
> Fix TrimmedString.trim test

- modules/core/shared/src/test/scala/eu/timepit/refined/types/CharTypesSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NumericTypesSpec.scala
Added some tests for refined types
> Improve specs

- modules/core/shared/src/test/scala/eu/timepit/refined/MaxSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/MinSpec.scala
> Reduce compilation times of {Max,Min}Spec

- build.sbt
The former definition is deprecated
> Replace import for crossProject

- notes/0.9.1.markdown
Add additional release notes for #503.
> Add change in TrimmedString behaviour to release notes

- modules/core/jvm/src/test/scala/eu/timepit/refined/StringValidateSpecJvm.scala
> Compare only parts of the Regex error message

- .travis.yml
- build.sbt
They have been disabled in https://github.com/fthomas/refined/pull/571
> Enable tests for 2.13.0-M5

- notes/0.9.3.markdown
This should contain all relevant changes between [0.9.2 and master](https://github.com/fthomas/refined/compare/v0.9.2...master).
> Prepare release notes for 0.9.3

- README.md
Many thanks for your awesome library, @fthomas ! 😬
> Add Colisweb to the list of companies using the library

- README.md
We are using refined in our financial systems :)
> Add FOLIO to list of adopters

- .travis.yml
- README.md
- build.sbt
- notes/0.9.8.markdown
Needs:
* https://github.com/rickynils/scalacheck/pull/479
> Update to Scala 2.13.0

- build.sbt
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SemigroupAndMonoidLawTests.scala
Manual update is required
Supersedes #710
> Update discipline-scalatest to 1.0.0-RC4

- modules/core/shared/src/test/scala/eu/timepit/refined/RefineSyntaxSpec.scala
> Do not check some error messages in syntax test

- project/build.properties
Reverts fthomas/refined#727
Releasing still fails with this version:
```
[error] sbt.librarymanagement.ResolveException: Error downloading org.scalacheck:scalacheck_native0.3_2.12:1.14.3
[error]   Not found
[error]   Not found
[error]   not found: /home/travis/.ivy2/local/org.scalacheck/scalacheck_native0.3_2.12/1.14.3/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalacheck/scalacheck_native0.3_2.12/1.14.3/scalacheck_native0.3_2.12-1.14.3.pom
[error] Error downloading org.scala-native:auxlib_native0.3_2.12:0.3.9
[error]   Not found
[error]   Not found
[error]   not found: /home/travis/.ivy2/local/org.scala-native/auxlib_native0.3_2.12/0.3.9/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scala-native/auxlib_native0.3_2.12/0.3.9/auxlib_native0.3_ …
```
> Revert "Update sbt to 1.3.8"

- modules/core/shared/src/test/scala/eu/timepit/refined/CollectionInferenceSpec.scala
See https://github.com/scala/scala/pull/8580#issuecomment-587340208.
> Do not check error message in CollectionInferenceSpec

- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NetTypesSpec.scala
Fix Rfc1918 class B IP start range issue described in #702
> Rfc1918 class B IP must start from 172.16 and not 172.15

- .travis.yml
- build.sbt
- project/plugins.sbt
> Drop support for Scala.js 0.6

- modules/core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
... because Stream is deprecated since 2.13.0.
> Use Iterator instead of Stream in tryN

- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
This fixes compilation errors on Dotty.
> Deprecate companions of already deprecated classes

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/collection.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/types/string.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/collection.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/types/string.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/CollectionInferenceSpec.scala
- modules/pureconfig/shared/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
- modules/shapeless/shared/src/test/scala/eu/timepit/refined/shapeless/typeable/TypeableSpec.scala
See https://github.com/fthomas/refined/pull/841#issuecomment-699502818.
> Use Int literals for numeric predicates like Positive

- modules/scalacheck/shared/src/test/scala-3.0-/eu/timepit/refined/scalacheck/CollectionArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala-3.0-/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
> Do not use Nat in scalacheck tests

- build.sbt
- latestVersion.sbt
> Don't use partial function in MiMa setting

- build.sbt
See https://github.com/raquo/Laminar/pull/91 why we're doing this.
> Use GitHub URLs instead of local paths in SJSIR files

- README.md
> Add calypso to projects

- README.md
[Contentsquare](https://contentsquare.com/) uses refined in production.
I recently wrote a piece about how and why we use the library: https://engineering.contentsquare.com/2021/scala-refined-types/
> Add Contentsquare as adopter

- README.md
"by" was missing in "[…] was inspired this library […]"
> Add missing "by"

- README.md
This pull request adds a new entry to the adopters list in README.md file
> Add PITS Global Data Recovery Services to the adopters list

- build.sbt
- https://github.com/fthomas/refined/pull/1193
> remove shapeless imports from initialCommands

- README.md
Hi Frank,
We are happy users of refined. 
Regards from Copenhagen, Denmark :)
Viet
> Add Adopter: Hypefactors

- build.sbt
- doctest support scala-js and scala-native in latest version https://github.com/sbt-doctest/sbt-doctest/issues/52
> enable doctest for scala-js and scala-native
