- notes/0.3.0.markdown
- shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
`coflatMapRefine` is a generalization of `mapRefine` in the sense that `mapRefine` can be implemented in terms of `coflatMapRefine` and `unwrap`. What is interesting here is that this situation is similar to a `Comonad` where `map` can be implemented in terms of `coflatMap` and `extract` in exactly the same way.
> Add RefType.coflatMap

- notes/0.3.0.markdown
- shared/src/main/scala/eu/timepit/refined/util/time.scala
This adds the `util.time` module with these refined types:
* `Month`: an `Int` in the range from 1 to 12
* `DayOfMonth`: an `Int` in the range from 1 to 31
* `Hour`: an `Int` in the range from 0 to 23
* `Minute`: an `Int` in the range from 0 to 59
* `Second`: an `Int` in the range from 0 to 59
closes #64
> Add date- and time-related types

- build.sbt
- notes/0.3.1.markdown
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numericArbitrary.scala
- scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
This is just a draft of a possible `refined-scalacheck` module, see #58. It only has an `Arbitrary` instance for `F[T, Interval[H, L]]` but there are a few others which should be just as easy to write (e.g. `Letter`, `Digit`, `EndsWith`, `StartsWith`, `Empty`, `Size`, etc.). 
@koshelev since you was the first to ask for this, do you have any specific predicates in mind for which we should provide `Arbitrary` instances?
> First draft of a scalacheck module

- notes/0.3.2.markdown
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/any.scala
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/boolean.scala
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/char.scala
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/string.scala
- scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/CharArbitrarySpec.scala
- scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
This is consistent with the naming of modules under `eu.timepit.refined.util.string`.
> Remove Arbitrary suffix from scalacheck modules

- README.md
- core/jvm/src/test/scala/eu/timepit/refined/GenericValidateSpecJvm.scala
- core/shared/src/main/scala/eu/timepit/refined/generic.scala
- core/shared/src/test/scala/eu/timepit/refined/GenericValidateSpec.scala
- notes/0.3.2.markdown
This adds the `Eval` predicate that takes a `String` singleton type as parameter. The value of that singleton type is a definition of a predicate `T => Boolean` which is parsed and evaluated at compile-time to check if a given value satisfies it. `Eval` allows to define arbitrary predicates without writing `Validate` instances.
Example usage:
```scala
scala> type IsEven = Eval[W.`"(x: Int) => x % 2 == 0"`.T]
defined type alias IsEven
scala> val a: Int @@ IsEven = 4
a: shapeless.tag.@@[Int,IsEven] = 4
scala> val b: Int @@ IsEven = 5
<console>:47: error: Predicate failed: (x: Int) => x % 2 == 0.
val b: Int @@ IsEven = 5
^
```
> Add Eval predicate

- build.sbt
- core/shared/src/test/scala/eu/timepit/refined/RefineSyntaxSpec.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.3.2.markdown
- scalaz/src/main/scala/eu/timepit/refined/scalaz/auto.scala
- scalaz/src/main/scala/eu/timepit/refined/scalaz/package.scala
- scalaz/src/test/scala/eu/timepit/refined/scalaz/RefTypeSpecScalazTag.scala
This provides a `RefType` instance for `scalaz.@@`. My main motivation for this is to see how `scalaz.@@` compares to `shapeless.tag.@@` and `Refined` as carrier for refinements.
> Draft of a refined-scalaz subproject

- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/RefineMFullyApplied.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.3.3.markdown
`refineMF` is a variation of `refineM` but which requires that the base type is specified before `apply` can be called. This allows to create aliases like `val Natural = RefType[Refined].refineMF[Long, NonNegative]` which only can be called with `Long` arguments.
closes #107
/cc @jedesah and @wemrysi
> Add RefType.refineMF

- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- contrib/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- Remove hardcoded Int
- Add instances for shapeless.Nat
> [WIP] Revamp instances of Arbitrary for Numeric

- README.md
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- contrib/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- notes/0.3.3.markdown
This expands on #106 by using four helper functions to implement all numeric `Arbitrary` instances independent of the predicates being indexed by literal singleton types or `Nat`s. I think that is the best we can do to avoid duplication in those definitions.
Thanks to @jedesah for the initial implementation!
@jedesah I hope you don't mind moving this forward. I think it is in your interest to get this and #108 released ASAP.
> Arbitrary instances for numeric predicates indexed by Nats

- build.sbt
- project/plugin-mima.sbt
Revert fthomas/refined#110 because it caused nondeterministic build errors.
> Revert "Use MiMa to detect binary compat issues"

- contrib/scalaz/src/main/scala/eu/timepit/refined/scalaz/package.scala
- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/InferMacro.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.3.4.markdown
This has the advantage that we don't need to eval `RefType` instances during macro expansion which is somewhat error prone (see #3).
> Remove macro code from RefType

- contrib/scalaz/src/main/scala/eu/timepit/refined/scalaz/auto.scala
- core/shared/src/main/scala/eu/timepit/refined/auto.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/RefineMFullyApplied.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/RefineMPartiallyApplied.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/InferMacro.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
The standard in the code base is that an implicit RefType comes always
before a Validate or Inference parameter.
> Reorder implicits parameters in macros

- contrib/scalacheck/jvm/src/test/scala/eu/timepit/refined/scalacheck/util/OurMathSpec.scala
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/util/Adjacent.scala
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/util/Bounded.scala
- contrib/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/util/OurMath.scala
- contrib/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- contrib/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/util/AdjacentSpec.scala
- notes/0.3.7.markdown
This adds an `Adjacent` type class to `refined-scalacheck` to make the numeric `Arbitrary` instances more robust. The type class allows to get rid of `filter` calls in the numeric generators.
> Add Adjacent type class

- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefPartiallyApplied.scala
- notes/0.3.8.markdown
This changes the return type of `ApplyRefPartiallyApplied.apply`
such that `res0` in the following example contains `Natural`:
```scala
scala> type Natural = Long Refined NonNegative
defined type alias Natural
scala> RefType.applyRef[Natural](4L)
res0: Either[String,Natural] = Right(Refined(4))
```
Without this change, we get:
```scala
scala> RefType.applyRef[Natural](4L)
res0: Either[String,Long Refined NonNegative] = Right(Refined(4))
```
> Fix return type of ApplyRefPartiallyApplied.apply

- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefMPartiallyApplied.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.3.8.markdown
Add `RefType.applyRefM`, the the macro variant of `RefType.applyRef`.
`applyRefM` is useful when working with type aliases for refined
types and without any implicits, for example:
```scala
scala> type Natural = Long @@ NonNegative
defined type alias Natural
scala> RefType.applyRefM[Natural](42L)
res0: Natural = 42
```
Closes #112.
> Add RefType.applyRefM

- core/shared/src/main/scala-2.10/eu/timepit/refined/api/Refined.scala
- core/shared/src/main/scala-2.11/eu/timepit/refined/api/Refined.scala
- core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- docs/namestartchar.md
- docs/type_aliases.md
- notes/0.3.8.markdown
The rationale for this change is that the sole purpose of types like `@@` and `Refined` (which are refinement carrier) is to attach a predicate to a base type. Ideally the carrier itself has no effect at runtime. Therefore the string representation of a refined type should be just the string representation of the base type. Note that this is already the case for `@@`.
> Delegate Refined#toString to the underlying value

- build.sbt
- core/shared/src/main/scala/eu/timepit/refined/api/Validate.scala
- core/shared/src/main/scala/eu/timepit/refined/boolean.scala
- core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- core/shared/src/test/scala/eu/timepit/refined/RefineMSpec.scala
- docs/ctorfieldnames.md
- docs/src/ctorfieldnames.md
- notes/0.3.8.markdown
This removes the notion of "constant" `Validate` instances
that allowed to refine non-literal values at compile-time.
This feature hasn't proven to be useful after all.
See #26 for the original issue that introduced constant
predicates.
> Remove notion of constant Validate instances

- README.md
- core/shared/src/main/scala/eu/timepit/refined/collection.scala
This changes all collection predicates that required a
TraversableOnce to require a Traversable instead. Refining
is pointless if the values of a collection can't be accessed
anymore after refining.
> Require a Traversable for collection predicates

- core/jvm/src/test/scala/eu/timepit/refined/GenericValidateSpecJvm.scala
- core/shared/src/main/scala/eu/timepit/refined/generic.scala
- notes/0.4.1.markdown
This makes parameter types of function literals in the `Eval` predicate
optional. It allows to write
```scala
val x: Int Refined Eval[W.`"x => x > 0"`.T] = 1
```
instead of
```scala
val y: Int Refined Eval[W.`"(x: Int) => x > 0"`.T] = 1
```
> Make parameter types of function literals optional

- build.sbt
- core/shared/src/main/scala-2.10/eu/timepit/refined/api/Refined.scala
- core/shared/src/main/scala-2.11/eu/timepit/refined/api/Refined.scala
- core/shared/src/test/scala/eu/timepit/refined/RefinedSpec.scala
.. with before-and-after (newly created) spec changes
> Drop case in Refined

- .travis.yml
This is in anticipation for Scala 2.12 and #157 which both
require Java 8.
> Stop compiling with JDK 7

- core/shared/src/main/scala/eu/timepit/refined/internal/ApplyRefPartiallyApplied.scala
- core/shared/src/main/scala/eu/timepit/refined/internal/RefinePartiallyApplied.scala
- core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.4.1.markdown
... and add `ApplyRefPartiallyApplied.unsafeFrom`. These methods
refine an unrefined value and throw an exception in case the value
does not satisfy the predicate.
> Rename force to unsafeFrom

- build.sbt
- core/shared/src/main/scala-2.10/eu/timepit/refined/api/Refined.scala
- core/shared/src/main/scala-2.11/eu/timepit/refined/api/Refined.scala
Without this change the following code compiles without warnings:
```scala
Refined.unsafeApply(0) match {
case Refined(x) => true
case _ => false
}
```
although the second match can never be reached. If we refine the
the return type of `Refined.unapply` from `Option[T]` to `Some[T]`,
the compiler emits a warning about unreachable code in the example
above:
```
[error] RefinedSpec.scala:38: unreachable code
[error]       case _ => false
[error]                 ^
```
> Use Some[T] instead of Option[T] as return type

- build.sbt
This currently fails because shapeless 2.3.2 is not yet available for 2.12.0-RC2.
> Build with 2.12.0-RC2

- core/shared/src/main/scala/eu/timepit/refined/auto.scala
This example shows that `autoUnwrap` implicitly converts refined
types to its base type if needed. I hope this clarifies its purpose.
Closes: #218
> Add example to autoUnwrap's Scaladoc

- README.md
- build.sbt
- contrib/pureconfig/jvm/src/main/scala/eu/timepit/refined/pureconfig/error/PredicateFailedException.scala
- contrib/pureconfig/jvm/src/main/scala/eu/timepit/refined/pureconfig/package.scala
- contrib/pureconfig/jvm/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
Adds a `refined-pureconfig` project containing a tiny integration with [pureconfig](https://github.com/melrief/pureconfig).  
I've tried to keep things as similar as possible to `refined-scodec` where possible.
> Add refined-pureconfig

- contrib/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- core/shared/src/main/scala/eu/timepit/refined/types/AllTypes.scala
- core/shared/src/main/scala/eu/timepit/refined/types/NumericTypes.scala
- core/shared/src/main/scala/eu/timepit/refined/types/TimeTypes.scala
- core/shared/src/main/scala/eu/timepit/refined/types/package.scala
- notes/0.6.2.markdown
This is a draft that adds type aliases for standard refined types such as `Int Refined Positive` or `Int Refined Negative` as proposed in #185. Names of these type aliases are up to debate but I think the current scheme for numeric types is both precise and scalable. Having these aliases in the core module does not force their usage on users. Users are still free to use whatever name they like.
/cc @benhutchison
> Add aliases for standard refined types

- build.sbt
The `Xml` predicate requires that dependency which was transitively
pulled in via the dependency on `scala-compiler`.
> Add explicit dependency on scala-xml

- build.sbt
- latestVersion.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
- modules/docs/macro_pitfalls.md
- modules/docs/nonnegint.md
- modules/docs/type_aliases.md
- modules/docs/util_string.md
- modules/eval/jvm/src/test/scala/eu/timepit/refined/GenericValidateSpecJvm.scala
- modules/eval/shared/src/main/scala/eu/timepit/refined/eval.scala
- project/LatestVersion.scala
- version.sbt
Fixes #207
I rejiggered the parts of the build related to binary dependency checking a bit and bumped the version to 0.7.0 (-SNAPSHOT), since the change is breaking.
> Move compiler-dependent code into a module

- modules/core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
by calling `duplicate` before untypechecking the tree.
This is an attempt to fix https://github.com/fthomas/refined/issues/260
> Improve MacroUtils.eval

- build.sbt
- latestVersion.sbt
- modules/pureconfig/jvm/src/main/scala/eu/timepit/refined/pureconfig/error/PredicateFailedException.scala
- modules/pureconfig/jvm/src/main/scala/eu/timepit/refined/pureconfig/package.scala
- modules/pureconfig/jvm/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
- version.sbt
Outstanding questions:
- ~~We need to populate the `toTyp` parameter of `CannotConvert` with a `String` representation of `F[T, P]`. I don't see a straightforward way to do this without using type tags, and we would then lose any type aliases. Adding the type tag breaks binary compatibility (according to MiMa).~~
- ~~`PredicateFailedException` is now unused but has not been removed as that would break binary compatibility (according to MiMa).~~
> Change refined-pureconfig to use pureconfig 0.6.0

- build.sbt
- latestVersion.sbt
- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/package.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/CatsSpec.scala
This adds cats `Show` and `Eq` instances for refined types, similar to the scalaz module.
> Show and Eq instances for cats

- project/plugin-bintray.sbt
Reverts fthomas/refined#285 because of this error during the last release:
```
> coreJVM/bintraySyncMavenCentral
[trace] Stack trace suppressed: run last coreJVM/*:bintraySyncMavenCentral for the full output.
[error] (coreJVM/*:bintraySyncMavenCentral) java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
[error] Total time: 0 s, completed Jun 3, 2017 12:12:32 AM
>
> last coreJVM/*:bintraySyncMavenCentral
java.lang.NoSuchMethodError: org.json4s.Formats.emptyValueStrategy()Lorg/json4s/prefs/EmptyValueStrategy;
at org.json4s.native.JsonMethods$class.render(JsonMethods.scala:29)
at org.json4s.native.JsonMethods$.render(JsonMethods.scala:62)
at bintry.Methods$json$.str(Methods.scala:19)
at …
```
> Revert "Update to sbt-bintray 0.4.0"

- README.md
PureConfig managed to snag the `pureconfig` org on github, so its official location shifted.
> Update PureConfig URL

- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
fixes #296 
```
scala> refineV[Uuid](java.util.UUID.randomUUID.toString)
res0: Either[String,eu.timepit.refined.api.Refined[String,eu.timepit.refined.string.Uuid]] = Right(15928f6a-fa6f-49db-bd96-32ca7b17eb39)
scala> refineV[Uuid](java.util.UUID.randomUUID.toString.toUpperCase)
res1: Either[String,eu.timepit.refined.api.Refined[String,eu.timepit.refined.string.Uuid]] = Right(DEA52FDE-267D-404E-83B1-311731F8A7A4)
scala> refineV[Uuid]("whops")
res2: Either[String,eu.timepit.refined.api.Refined[String,eu.timepit.refined.string.Uuid]] = Left(Uuid predicate failed: Invalid UUID string: whops)
scala> refineV[Uuid]("1-1-1-1-1")
res3: Either[String,eu.timepit.refined.api.Refined[String,eu.timepit.refined.string.Uuid]] = Left(Uuid predicate failed: requirement failed)
scala> …
```
> Improve uuidValidate

- README.md
```scala
// Fully refined type: type (Int) with predicate (here: 7 <= value <= 77).
type Age = Int Refined Interval.ClosedOpen[W.`7`.T, W.`77`.T]
val userInput = 55
// With typed value declaration.
val ageEither1 : Either[String, Age] = refineV(userInput)
println(ageEither1)
// With inferred type value.
val ageEither2 = RefType.applyRef[Age](userInput)
println(ageEither2)
```
> Example usge of "fully refined type" (Type + Predicate)

- README.md
- build.sbt
- project/plugin-ghpages.sbt
- project/plugin-site.sbt
... and stop publishing latest API docs to GitHub pages.
> Use javadoc.io for apiURL

- modules/core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- notes/0.8.4.markdown
This avoids to call `eval` for known `RefType` instances in
`RefineMacro.impl`. This is similar to #330 but more general
since it is an optimization for all macros in the library and
not only for `autoRefine{V,T}`.
The performance improvements are similar to that of #330:
```
[info] Result "eu.timepit.refined.benchmark.RefineMacroBenchmark.autoRefineV_PosInt":
[info]   0.408 ±(99.9%) 0.003 s/op [Average]
[info]   (min, avg, max) = (0.387, 0.408, 0.442), stdev = 0.012
[info]   CI (99.9%): [0.405, 0.411] (assumes normal distribution)
[info] # Run complete. Total time: 00:09:11
[info] Benchmark                                Mode  Cnt  Score   Error Units
[info] RefineMacroBenchmark.autoRefineV_PosInt  avgt  200  0.408 ± 0.003 s/op
```
> Do not use eval for known RefType instances

- build.sbt
- modules/benchmark/src/main/scala/eu/timepit/refined/benchmark/InferMacroBenchmark.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/InferMacro.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- notes/0.8.4.markdown
This is the same as #332 but for `InferMacro`.
> Use refTypeObj in InferMacro

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/InferMacro.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- notes/0.8.4.markdown
This avoids to call `eval` for a few `Validate` instances in
`RefinedMacro.impl`. This is similar in spirit to #332.
For the `autoRefineV_PosInt` benchmark we get a decrease in compilation
time of ~56% (or ~67% prior to #332):
```
[info] Result "eu.timepit.refined.benchmark.RefineMacroBenchmark.autoRefineV_PosInt":
[info]   0.181 ±(99.9%) 0.001 s/op [Average]
[info]   (min, avg, max) = (0.173, 0.181, 0.234), stdev = 0.006
[info]   CI (99.9%): [0.180, 0.182] (assumes normal distribution)
[info] # Run complete. Total time: 00:08:03
[info] Benchmark                                Mode  Cnt  Score   Error Units
[info] RefineMacroBenchmark.autoRefineV_PosInt  avgt  200  0.181 ± 0.001 s/op
```
> Do not use eval for some Validate instances

- modules/benchmark/src/main/scala/eu/timepit/refined/benchmark/RefineVBenchmark.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Validate.scala
- notes/0.8.4.markdown
Motivation for this is the considerable effect on the newly added
benchmark:
```
master:
[info] Benchmark                          Mode  Cnt   Score   Error Units
[info] RefineVBenchmark.refineV_Positive  avgt  200  27.557 ± 0.298 ns/op
this branch:
[info] Benchmark                          Mode  Cnt   Score   Error Units
[info] RefineVBenchmark.refineV_Positive  avgt  200  20.605 ± 0.156 ns/op
```
> Inline Validate.instance in Validate.fromPredicate

- modules/benchmark/src/main/scala/eu/timepit/refined/benchmark/RefineVBenchmark.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Validate.scala
- notes/0.8.4.markdown
Benchmark results for this change:
```
master:
[info] Result "eu.timepit.refined.benchmark.RefineVBenchmark.refineV_Regex":
[info]   121.400 ±(99.9%) 1.297 ns/op [Average]
[info]   (min, avg, max) = (110.969, 121.400, 159.030), stdev = 5.493
[info]   CI (99.9%): [120.103, 122.698] (assumes normal distribution)
[info] # Run complete. Total time: 00:06:43
[info] Benchmark                       Mode  Cnt    Score   Error  Units
[info] RefineVBenchmark.refineV_Regex  avgt  200  121.400 ± 1.297  ns/op
this branch:
[info] Result "eu.timepit.refined.benchmark.RefineVBenchmark.refineV_Regex":
[info]   108.263 ±(99.9%) 0.893 ns/op [Average]
[info]   (min, avg, max) = (100.935, 108.263, 138.393), stdev = 3.780
[info]   CI (99.9%): [107.370, 109.156] (assumes normal distribution)
[info] # Run …
```
> Optimize Validate.fromPartial

- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
A `String` that contains no leading or trailing whitespace.
This type is [dedicated](https://twitter.com/lunaryorn/status/851465290760278017) to @lunaryorn. :-)
> Add TrimmedString

- README.md
This list currently lives in the wiki where (I think) it is mostly ignored. Moving it back to the README gives projects that provide integrations with refined much more attention.
> Move list of projects using refined back to README

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/StringValidateSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NetSpec.scala
Basically a follow-up to #353
This is what I am using at work, I figured I would clean it up and contribute it back.
No external Java dependencies, so this also works with Scala.js without any issues.
I will have to add IPv6 next week, so I will send that in as well once I have it.
/cc @derekmorr @fthomas
> Add IPv4 and private networks

- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
Without parens, the type is parsed as:
```scala
(((String Refined Rfc1918PrivateSpec) Or
Rfc5737TestnetSpec) Or
Rfc3927LocalLinkSpec) Or
Rfc2544BenchmarkSpec
```
> Add parens to the predicate of PrivateNetwork

- build.sbt
- modules/scodec/shared/src/main/scala/eu/timepit/refined/scodec/predicates/byteVector.scala
- modules/scodec/shared/src/test/scala/eu/timepit/refined/scodec/predicates/ByteVectorValidateSpec.scala
- notes/0.8.5.markdown
This is still WIP and for now only contains an instance for `Size`.
Example usage:
```scala
scala> refineV[Size[Equal[W.`2L`.T]]](ByteVector.fromValidHex("0xabcd"))
res0: Either[String, Refined[ByteVector, Size[Equal[Long(2L)]]]] = Right(ByteVector(2 bytes, 0xabcd))
scala> refineV[Size[Equal[W.`2L`.T]]](ByteVector.fromValidHex("0xabcdef"))
res1: Either[String, Refined[ByteVector, Size[Equal[Long(2L)]]]] = Left(Predicate taking size(ByteVector(3 bytes, 0xabcdef)) = 3 failed: Predicate failed: (3 == 2).)
```
This implements #363. /cc @coltfred
> Collection validate instances for ByteVector

- README.md
- modules/scodec/shared/src/main/scala/eu/timepit/refined/scodec/byteVector.scala
- modules/scodec/shared/src/test/scala/eu/timepit/refined/scodec/ByteVectorValidateSpec.scala
This aligns the organization of `Validate` instances with
the core module.
> Remove "predicates" package from refined-scodec

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedType.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedTypeOps.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/char.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/time.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NumericTypesSpec.scala
- notes/0.8.5.markdown
This is a solution for #342 but unlike #346 it does not add a new macro. Compared to a macro solution, companion objects need be written manually and require a little bit boilerplate. E.g. for a refined type `type PosInt = Int Refined Positive` one would need to write a companion that extends from `RefinedTypeOps` like this:
```scala
object PosInt extends RefinedTypeOps[PosInt, Int]
```
Usage then looks like:
```scala
scala> PosInt(5)
res4: PosInt = 5
scala> PosInt(-5)
<console>:51: error: Predicate failed: (-5 > 0).
PosInt(-5)
^
scala> PosInt.from(5)
res6: Either[String,PosInt] = Right(5)
scala> val PosInt(x) = 5
x: PosInt = 5
```
So this PR adds the `RefinedTypeOps` class to simplify the definition of companion objects of refined types, the `RefinedType` type class that combines …
> Add RefinedTypeOps for companion objects of refined types

- README.md
- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/package.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/CatsSpec.scala
Delegates to the `Order` instance for the wrapped type, in the same way as the `Eq`/`Show` instances
> Add `Order` instance to cats module

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/package.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/CatsSpec.scala
Without shadowing, the `Order` instance is used in this test
because `Order` is a subtype of `Eq`.
> Shadow cats.Order instance in the cats.Eq test

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/StringValidateSpec.scala
Adds the following string predicates: `ValidInt`, `ValidLong`, `ValidDouble`, `ValidBigInt`, and `ValidBigDecimal`.
I initially implemented this with a typeclass-based approach, e.g. `ParsableString[N]`, which the `Validate` instance would use, but it seemed to be double the work than just creating new predicates and the corresponding `Validate` instances. Both seem extensible enough, though I surmise that a typeclass-based approach would be a little less verbose, since supplying the typeclass instances would be enough to get started. @fthomas, if you think that that's a more sensible approach, then I can always update this PR.
I'm also thinking of adding inference instances for these, but I'll hold off for now until I can find a good way of doing it without copious amounts of copy and …
> Valid number string predicates

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/RefineMacro.scala
- notes/0.8.6.markdown
Adding `WeakTypeTag` context bounds on the `T` and `P` type parameters
allows to retrieve `Validate` instances for some types instead of
`eval`uating them. This optimization was implemented in #334 but did
not work here because of the missing `WeakTypeTag`s.
The big difference in compilation times of `impl` and `implApplyRef`
is gone now:
```scala
scala>
shapeless.test.compileTime("RefType[Refined].refineM[Positive](1)").toMillis
res20: Long = 66
scala>
shapeless.test.compileTime("RefType.applyRefM[PosInt](1)").toMillis
res21: Long = 62
```
Closes #387.
> Reduce compilation times of RefineMacro.implApplyRef

- modules/core/shared/src/test/scala/eu/timepit/refined/ImplicitScopeSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/TestUtils.scala
This tests that `Validate` and `Inference` instances are in the implicit
scope of their predicates and do not need to be imported explicitly.
I conducted https://github.com/fthomas/refined/pull/392 under the
premise that `Validate` and `Inference` instances were not in the implicit
scope of their predicates and using them would always require an
explicit import. For example, to refine with the `numeric.Positive`
predicate I thought a `numeric._` wildcard import was always necessary.
This tests show that this is not the case.
> Test that instances don't need to imported explicitly

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericValidateSpec.scala
Fixes #396.
This switches the `Validate` instances for `Modulo` to use `Integral` rather than `Numeric`. I've also kept the support for floating point types by having specific instances for them, though I'd vote for dropping this support.
I couldn't find a way to create a witness-style singleton for `Byte` and `Short` literals - hence they are not tested.
The change is **almost** binary-compatible. I've had to add an exclude for `ReversedMissingMethodProblem` - is that ok? I see there are other exclusions of this type already.
> Fix #396 by avoiding .toDouble in Modulo Validate

- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/GenericValidateSpec.scala
... because of https://github.com/fthomas/refined/issues/396
Using Numeric#fromInt should be safer for this instance.
> Do not use Numeric#toDouble in Equal's Validate instance

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Max.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Min.scala
This avoids repetition and is a little bit easier on the eyes.
Type inference will do the correct thing in these cases.
> Omit type parameters in rt.unsafeWrap

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Max.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Min.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/internal/Adjacent.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/internal/AdjacentSpec.scala
The `numericAdjacent` allowed to derive this
```scala
scala> internal.Adjacent[BigDecimal].nextUp(BigDecimal(1.0))
res1: BigDecimal = 2.0
```
which is invalid because there are uncountable many `BigDecimal`s
greater than 1.0 and less than 2.0.
> Make Adjacent[BigDecimal] non-derivable

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Max.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Min.scala
Like `LessEqual[N]` and `GreaterEqual[N]` instead of `Not[Greater[N]]`
and `Not[Less[N]]`. For me the non-negated predicates are easier to
understand.
> Use numeric type aliases for Min/Max instances

- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericValidateSpec.scala
- notes/0.8.7.markdown
> Add Modulo[N, O] instance where N: Integral and O <: Nat

- modules/core/shared/src/main/scala/eu/timepit/refined/types/numeric.scala
I added some floating-point types for convenience.
> Add refined floating-point types

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/StringValidateSpec.scala
Looks like IPv6 validation using a regex is what makes the most sense.
- I looked at `sun.net.util.IPAddressUtil` but that's an internal JDK API, not supposed to be used, not available for Scala.JS (it is the underlying implementation for `java.net.InetAddress`)
- `java.net.InetAddress` itself always tries to make DNS calls unless you convert the String into the address bytes. That would, however, require a lot of logic to undo compacting etc.
- Guava and Apache Commons Validator are JVM-only and fairly large
> Add IPv6 string validation

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Max.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/Min.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/internal/Adjacent.scala
This PR
1. makes `Adjacent` a subclass of `Ordering`
2. adds `next{Up,Down}OrNone` to `Adjacent`
3. changes `{Min,Max}.findValid` to throw an exception instead of
looping forever if it fails to find a next value satisfying the predicate
Making `Adjacent` a subclass of `Ordering` was not required technically
but is the right thing to do conceptually. The laws of `Adjacent` are
`nextUp(x) >= x` and `nextDown(x) <= x` for all `x`. To formulate these
laws we need `>=` and `<=` and hence any `Adjacent` needs to be
`Ordering`.
> Make Adjacent a subclass of Ordering

- .travis.yml
Reverts fthomas/refined#371 because of long build times on Travis CI.
> Revert "Test if this works with JDK 9"

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/GenericValidateSpec.scala
- notes/0.9.0.markdown
Because they are lacking practical relevance.
See also #386.
> Deprecate Subtype and Supertype predicates

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/all.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/boolean.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/char.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/collection.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/generic.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/CharValidateSpec.scala
- notes/0.9.0.markdown
This allows to import all predicates with `import predicates.all._`. The `AllPredicates` trait also allow us to create an even bigger über-import. It is one step towards #184.
With a `predicates` package it also makes sense to move the actual definitions of our predicates here. But that should happen in another PR.
> Add predicates package and über-import for all predicates

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/GenericValidateSpec.scala
- notes/0.9.0.markdown
because they operate on types and not values and refined focuses
on refining values.
> Deprecate ConstructorNames and FieldNames predicates

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/boolean.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/char.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/generic.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.9.0.markdown
- scalastyle-config.xml
This is the same as #392 but on top of current master.
> Reorganize type class instances

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
and make all their fields private now that the Validate instances
are defined inside the companions.
> Move IPv4 and IPv6 companions to the other companions

- modules/docs/macro_pitfalls.md
Added documentation to solve `java.lang.ClassNotFoundException` when adding a custom predicate inside a project (not REPL).
This addresses the issue #448
> Added documentation to solve exception during macro expansion errors

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericInferenceSpec.scala
If a value is greater than `x`, then it also must not be less than `x`.
What do you think of introducing it as an inference rule?
> Add inference rule for `Greater[A] ==> Not[Less[A]]`

- build.sbt
- latestVersion.sbt
- modules/shapeless/shared/src/main/scala/eu/timepit/refined/shapeless/typeable.scala
- modules/shapeless/shared/src/test/scala/eu/timepit/refined/shapeless/typeable/TypeableSpec.scala
Added a module for shapeless support of `Typeable`
> Added support to generate a Typeable for a refined type

- README.md
- build.sbt
- latestVersion.sbt
- modules/scopt/shared/src/main/scala/eu/timepit/refined/scopt/package.scala
- modules/scopt/shared/src/test/scala/eu/timepit/refined/scopt/RefTypeRedSpec.scala
Fixes #326.
I've done my best to respect the project's conventions, but feel free to point out anything I might have missed.
A couple of points:
* I had to enable scalaJS modules for `scoptJS`. I'm not entirely sure what ramifications this might have
* I cannot seem to run `validate` locally, as I'm getting some test failures. This is in the `core` module however and I'm assuming, for the moment, that it's to do with my local setup rather than with anything I might have done.
> Add scopt module

- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/all.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/collection.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/CollectionArbitrarySpec.scala
I thought I would get the ball rolling for collection arbitrary instances for ScalaCheck. I've added one instance for lists with a `MaxSize`, from here if the structure is OK I can add more as can other people.
> Add arbitrary instance for lists with a MaxSize.

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/package.scala
- modules/cats/shared/src/test/scala-2.12/eu/timepit/refined/cats/RefTypeMonadErrorSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/CatsSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/RefTypeContravariantSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/RefTypeMonadErrorSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
This is a port of #447 for Cats. One reason for doing this is to see if the 2.10 build fails in a similar way.
/cc @fommil
> Port of #447 for Cats

- build.sbt
This reverts one part of #462 (running tut in a forked JVM)
which should not be necessary anymore. I hope running the
tests in a forked JVM should be enough to fix the OOME
that #462 tried to fix.
> Try stabilizing 2.10 build by running tests in a forked JVM

- build.sbt
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/collection.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/string.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/CollectionArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
This builds up on the work @matthedude did in #455 to provide `Arbitrary` instances for `Vector` and `String` with any `Size[P]` predicate.
The instance for `String` will become handy if we add something like `FiniteString[N]` (#437) to the library.
> Arbitrary instances for Vector/String with Size[P]

- build.sbt
- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedType.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/reftype.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
- notes/0.9.0.markdown
A `String` with length less than or equal to `N`.
This adds the type alias `FiniteString[N]` and a function to create
"companion objects" for `FiniteString`s of the given max length.
closes #437
> Add FiniteString[N]

- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/AnyArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/CharArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/CollectionArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/GenericArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/PackageSpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
... instead of `checkArbitraryRefType`. The former can also check
`Arbitrary` instances of type aliases.
> Use checkArbitraryRefinedType

- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/util/Adjacent.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/util/Bounded.scala
- notes/0.9.0.markdown
This replaces `Bounded` in the scalacheck module with `Min` and `Max`
from the core module. This is similar to #393 but just modifies the
implicit parameters of the current instances.
> Replace Bounded with Min & Max

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/StringValidateSpec.scala
- notes/0.9.1.markdown
- ValidByte
- ValidShort
- ValidFloat
> Add predicates for string

- modules/benchmark/src/main/scala/eu/timepit/refined/benchmark/PosIntBenchmark.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedType.scala
- notes/0.9.1.markdown
- project/plugin-jmh.sbt
Before this change:
[info] Result
"eu.timepit.refined.benchmark.PosIntBenchmark.unsafeFrom_1":
[info]   23.575 ±(99.9%) 0.264 ns/op [Average]
[info]   (min, avg, max) = (22.521, 23.575, 29.684), stdev = 1.119
[info]   CI (99.9%): [23.311, 23.840] (assumes normal distribution)
[info] # Run complete. Total time: 00:06:43
[info] Benchmark                     Mode  Cnt   Score   Error  Units
[info] PosIntBenchmark.unsafeFrom_1  avgt  200  23.575 ± 0.264  ns/op
After this change:
[info] Result
"eu.timepit.refined.benchmark.PosIntBenchmark.unsafeFrom_1":
[info]   13.410 ±(99.9%) 0.076 ns/op [Average]
[info]   (min, avg, max) = (12.855, 13.410, 14.228), stdev = 0.323
[info]   CI (99.9%): [13.334, 13.487] (assumes normal distribution)
[info] # Run complete. Total time: 00:06:43
[info] Benchmark …
> Improve performance of RefinedType#unsafeFrom

- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/all.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/string.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
- scalastyle-config.xml
This also adds `TrimmedString.trim` and is a replacement for #487 based
on the discussion there.
While we are at it I threw in an `Arbitrary` instance for `TrimedString`.
> Replace TrimmedString regex with Trimmed predicate type

- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefType.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedTypeOps.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/internal/RefineMFullyApplied.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/api/RefTypeSpec.scala
- notes/0.9.1.markdown
`RefineMFullyApplied` provides a subset of the functionality of `RefinedTypeOps` so we can replace the former with the latter.
This is one step towards #386.
> Deprecate RefType#refineMF in favor of RefinedTypeOps

- build.sbt
Scala Native is only available for 2.11, so scalaVersion for
`coreNative` and all other Native projects should be a 2.11 version.
closes #524
> Restrict Scala Native projects to Scala 2.11

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/syntax.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
Adds a `refinedSize` extension method that returns the size of a NonEmptyList as a positive int.
Based on [this Twitter thread](https://twitter.com/LukaJacobowitz/status/1015216561152577536), at least 2 people in the world want this 😄
> Add syntax for Cats NonEmptyList

- build.sbt
so that `sbt doc` won't recompile sources.
> Do not turn coverage off in validateJVM

- README.md
Documentation for `IPv4`, `IPv6` and `Trimmed` is currently missing in the README.
> Added documentation to README for missing string predicates

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/digests.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
I believe that this PR brings `HexStringSpec` in line with the layout used in refined. See for example `LetterOrDigit` in https://github.com/fthomas/refined/blob/0820276b7cc80390a7cec5ecb353507376167a7f/modules/core/shared/src/main/scala/eu/timepit/refined/char.scala
> Moved HexStringSpec and added documentation to README

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/all.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/predicates/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/all.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/numeric.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/NumericValidateSpec.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/all.scala
- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/numeric.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/NumericArbitrarySpec.scala
As previously discussed in the gitter channel.
There is some duplication for `Float` and `Double`, the only types with a NaN value. I've considered adding a `HasNaN[A]` typeclass to reduce duplication, but ultimately thought the complexity was unwarranted in this case. If the maintainers think otherwise, I'd happy to make this change though.
> Added `NotNaN` predicate

- modules/core/shared/src/main/scala/eu/timepit/refined/auto.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/AutoSpec.scala
- notes/0.9.5.markdown
> Add type param to autoUnwrap to improve type inference

- README.md
see https://typelevel.org/blog/2019/05/01/typelevel-switches-to-scala-code-of-conduct.html
> Switch to Scala Code of Conduct

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/syntax.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
I think it may be useful _(at least it is for me 😅)_.
Uhm, I just realized that the rename from `validate` to `validateNel` would break existing code...
Would you want me to leave it as `validate`, or keep both `validate` & `validateNel` _(maybe in a future deprecate the first?)_.
> Cats validatenec

- build.sbt
- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/Shift.scala
- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/package.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/RefTypeMonadErrorSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SemigroupAndMonoidLawTests.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SemigroupSpec.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/ShiftSpec.scala
This merge request partially fixes https://github.com/fthomas/refined/issues/527. It adds:
- semigroup instances for Positive and Negative numeric types (Byte, Short, Int, Long, Float and Double)
- monoid instances for NonPosFloat, NonPosDouble and NonNegative numeric types (Byte, Short, Int, Long, Float and Double) 
- law tests for these instances. Law tests for Float and Double are commented (as done in [cats tests](https://github.com/typelevel/cats/blob/v1.6.0/kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala#L218)), because floating point addition is not associative.
As discussed in https://github.com/fthomas/refined/issues/527, the instances overflow for Integral types.
FYI, I tried adding monoid instances for NonPositive Integral types, but they are not associative:
``` …
```
> add semigroup and monoid instances for numeric types

- modules/core/shared/src/main/scala/eu/timepit/refined/api/Validate.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/macros/MacroUtils.scala
This change might prevent the compiler crash reported in #260 by removing the self type in `Validate` (see https://github.com/fthomas/refined/issues/260#issuecomment-574623965). Since I haven't been able to reproduce or even observe the crash in #260, I can't say if this actually improves anything.
> Do not use self type in Validate

- build.sbt
if set `-Duser.language=ja`
https://travis-ci.org/xuwei-k/refined/jobs/657092376#L1887
```
failing seed for StringValidate.Xml.showResult is JM9OWVbVeuRDnptFtOfwU-0lbs8XXj59Gu7jiF0R7GE=
[info] ! StringValidate.Xml.showResult: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] Expected "Xml predicate failed: XML document structures must start and end within the same entity." but got "Xml predicate failed: XMLドキュメント構造は、同じエンティティ内で開始および終了する必要があります。"
[info] + StringValidate.XPath.isValid: OK, proved property.
failing seed for StringValidate.XPath.showResult is -xPWjCC6cDN_IQGuY7bnJFPE5wzl9KeRsUkycqsB0pN=
[info] ! StringValidate.XPath.showResult: Falsified after 0 passed tests.
[info] > Labels of failing property: 
[info] Expected "XPath predicate failed: …
```
> fix StringValidateSpecJvm in another locale

- .travis.yml
- build.sbt
- modules/scodec/shared/src/test/scala/eu/timepit/refined/scodec/RefTypeCodecSpec.scala
- project/build.properties
- project/plugins.sbt
This PR contains fixes to partially support Scala.js 1.0.0
There are some important notes
`scalaz` and `scopt` are ommited. The first requires some code changes and the second has a conflict on the way the `OS` object is used that conflicts with scala.js
`scoverage` was disabled as well
It should be possible to run this on 0.6.32 and dual release
How is release handled?
> Support scala.js 1.0

- README.md
[**neotypes**](https://neotypes.github.io/neotypes/) is a Scala lightweight, type-safe, asynchronous driver for neo4j. And we provide a module to allow inserting and reading refined types.
And we would like to be added on the external modules list.
> Adding neotypes to the external modules list

- modules/core/shared/src/main/scala/eu/timepit/refined/types/all.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
- modules/scalacheck/shared/src/test/scala/eu/timepit/refined/scalacheck/StringArbitrarySpec.scala
This type is a conjunction of the existing FiniteString and NonEmptyString types.
In our codebase at work, we often have to deal with strings that are both non-empty and finite of length. I thought this could be a useful addition to refined, rather than just having it privately in our codebase.
I'll comment down below on things that I am not sure of or that are currently broken that I don't know how to fix.
> Add new NonEmptyFiniteString type

- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
This function was proposed before by @Hjdskes in https://github.com/fthomas/refined/pull/760#issuecomment-614248478. I argued against adding it if nobody is needing it right now. After looking at our codebase at $WORK again I found out that we are using exactly this function for our custom `NonEmptyFiniteString`. So at least we would benefit from an official `NonEmptyFiniteString.truncate`. :-)
> Add NonEmptyFiniteString.truncate function

- modules/scalacheck/shared/src/main/scala/eu/timepit/refined/scalacheck/string.scala
It seems that new Arbitrary instances do not need to be added to
*BinCompatN traits any more since support for 2.11 has been dropped.
> uuidStringArbitrary does not need to be in StringInstancesBinCompat1

- modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/CollectionInferenceSpec.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
This allows, amongst others, the inference of `NonEmptyString` from `NonEmptyFiniteString`.
> Add Inference instance for Size[Interval.Closed[1, N]] ==> NonEmpty

- modules/core/shared/src/main/scala/eu/timepit/refined/types/net.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/NetTypesSpec.scala
> Fix Rfc1918ClassBPrivateSpec incorrect matches

- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
- modules/eval/shared/src/test/scala/eu/timepit/refined/EvalValidateSpec.scala
- modules/pureconfig/shared/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
- modules/scodec/shared/src/test/scala/eu/timepit/refined/scodec/RefTypeCodecSpec.scala
- modules/scopt/shared/src/test/scala/eu/timepit/refined/scopt/RefTypeReadSpec.scala
This will make a future Dotty transition easier.
> Do not use macros in tests of non-core modules

- build.sbt
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/RefTypeContravariantSpec.scala
For testing the Cats 2.2.0 Scalafix migration: https://github.com/scala-steward-org/scala-steward/pull/1588
> Update cats-core to 2.2.0-RC3

- modules/core/shared/src/main/scala/eu/timepit/refined/api/RefinedTypeOps.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/auto.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/util/string.scala
This will help a tiny bit porting refined to Dotty.
> Avoid Scala 2 macros in Scaladoc examples

- README.md
- modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala
`Traversable` is deprecated since 2.13.0 and should be replaced with
`Iterable`:
```
refined/modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala:99:15:
type Traversable in package scala is deprecated (since 2.13.0): Use Iterable instead of Traversable
[warn]         ev: T => Traversable[A]
[warn]               ^
```
> Replace Traversable with Iterable in collection predicates

- modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala
... to make Dotty happy. Without these changes, Dotty fails with errors
like these:
```
[error] -- [E008] Not Found Error: /home/frank/data/code/refined/modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala:197:14
[error] 197 |            t.lift(wn.value),
[error]     |            ^^^^^^
[error]     |            value lift is not a member of T
[error] -- [E008] Not Found Error: /home/frank/data/code/refined/modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala:263:31
[error] 263 |          val r = v.validate(t.size)
[error]     |                             ^^^^^^
[error]     |                             value size is not a member of T
```
> Make conversions in collection module explicit

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/api/RefType.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/api/RefType.scala
- modules/scalaz/shared/src/main/scala/eu/timepit/refined/scalaz/package.scala
The Dotty build currently fails with:
```
[error] -- [E043] Type Error: /home/travis/build/[secure]/refined/modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/api/RefType.scala:22:20
[error] 22 |  def unwrap[T](tp: F[T, _]): T
[error]    |                    ^^^^^^^
[error]    |   unreducible application of higher-kinded type F to wildcard arguments
```
This change should fix it.
> Do not use existential in RefType#unwrap to fix Dotty error

- build.sbt
It failed with:
```
java.lang.AssertionError: NoDenotation.owner while compiling eu.timepit.refined.BooleanInference0, eu.timepit.refined.BooleanInference1, eu.timepit.refined.BooleanInference2, eu.timepit.refined.CollectionInference, eu.timepit.refined.GenericInference, eu.timepit.refined.NumericInference, eu.timepit.refined.StringInference, eu.timepit.refined.api.Failed, eu.timepit.refined.api.Inference, eu.timepit.refined.api.LowPriorityMaxInstances, eu.timepit.refined.api.LowPriorityMinInstances, eu.timepit.refined.api.Max, eu.timepit.refined.api.MaxInstances, eu.timepit.refined.api.Min, eu.timepit.refined.api.MinInstances, eu.timepit.refined.api.Passed, eu.timepit.refined.api.RefType, eu.timepit.refined.api.Refined$package, eu.timepit.refined.api.RefinedType, …
```
> Disable Dottydoc to unblock publishing

- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanInferenceSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanValidateSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/CollectionInferenceSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/CollectionValidateSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/GenericInferenceSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/GenericValidateSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/MaxSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/MinSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/NumericInferenceSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/NumericValidateSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/RefineMSpec.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/api/RefTypeSpec.scala
This removes almost all usages of `shapeless.Nat` in tests to make
deprecating support of `Nat` easier.
> Prepare tests for deprecating support of Nat

- modules/core/shared/src/main/scala/eu/timepit/refined/types/string.scala
- modules/core/shared/src/test/scala/eu/timepit/refined/types/StringTypesSpec.scala
This PR adds the `truncateNes` method in `NonEmptyFiniteString[N]` as discussed on Gitter.
I'm not sure about how to write a test for this. Ideally, we'd add
```scala
property("""NEFString3.truncate(neStr)""") = forAll { (neStr: NonEmptyString) =>
val truncated = NEFString3.truncateNes(neStr)
truncated.value.length <= NEFString3.maxLength &&
(truncated.value ?= neStr.value.take(NEFString3.maxLength))
}
```
but this requires a dependency in `core` on `scalacheck`, which introduces a cycle that I am not sure how to resolve yet:
```
build.sbt:187: error: recursive lazy value core needs type
.dependsOn(core)
^
```
> Add NonEmptyFiniteString[N].truncateNes

- build.sbt
this turned up in the Scala community build, where of course we're testing nightlies
> in MiMa settings, don't blow up on Scala nightlies

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/syntax.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/SyntaxSpec.scala
I want to add `take` method to `NonEmptyList` and `NonEmptyVector` for convenience.
> Add take method to NonEmptyList and NonEmptyVector

- build.sbt
Depend on the ScalaCheck Scala 3 jar to avoid requiring downstream
consumers to also use the 2.13 ScalaCheck jar.
> Depend on ScalaCheck Scala 3 jar

- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/derivation.scala
- modules/cats/shared/src/main/scala/eu/timepit/refined/cats/unorderedFoldable.scala
- modules/cats/shared/src/test/scala/eu/timepit/refined/cats/UnorderedFoldableSpec.scala
This allows refining NonEmptyList et.al. which do not implement Iterable.
For some Foldables there of course exist higher performance implementations. However this implementation is very general and for NonEmptyList / NonEmptyChain at least is very similar with regard of performance.
Concerning the tests: I am not very happy with them because they also test logic outside of my implementation and rely on the String representations of predicates. Ideas welcome.
> Adds Validate[F[T], Size[P]] for every F[_]: Foldable.

- README.md
While browsing the README.md I noticed that the links to the Scala files in the "Provided Predicates" section are broken.
> Fix the links to the relevant Scala files

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/StringInferenceSpec.scala
Resolves my original issue #917 of unnecessary need of having `NonEmpty And ValidLong` once we know `ValidLong` is always non empty string.
> Inferences for various String refinement that are always non empty

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/boolean.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/boolean.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanInferenceSpec.scala
Agreed with @kubukoz that this PR will replace his https://github.com/fthomas/refined/pull/919.
I've suggested some naming, made one of inferences more generic, and added scala 3.0+ version.
> Add inference for #917

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/api/Refined.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/boolean.scala
Fixes #977. 
I added ``infix`` for all the types the compiler was complaining about when ``-source:future`` is enabled in the core module.
> Add infix operator to refined and boolean types

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/boolean.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/boolean.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/BooleanInferenceSpec.scala
> Move inferences to lower level of implicits, fixes #990

- README.md
This updated badge summarises which versions of Scala are supported by `refined` (and what the latest `refined` version is for each of those Scala versions):
[![refined Scala version support](https://index.scala-lang.org/fthomas/refined/refined/latest-by-scala-version.svg?color=blue)](https://index.scala-lang.org/fthomas/refined/refined)
More details on the badge format: https://github.com/scalacenter/scaladex/pull/660
> Update Scaladex badge on ReadMe to show Scala version support

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/string.scala
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/StringInferenceSpec.scala
Didn't add tests for Scala 3, see https://github.com/fthomas/refined/issues/928
> Add MatchesRegex ==> NonEmpty inference

- README.md
The `collection` URL is broken, so fixed it  according to #905.
> Fix README `collection` URL

- .github/workflows/ci.yml
- .jvmopts
- build.sbt
- modules/core/shared/src/test/scala-3.0-/eu/timepit/refined/StringValidateSpec.scala
- project/plugins.sbt
Closes https://github.com/fthomas/refined/issues/1090.
This restores the Native builds for core, scalacheck, and shapeless modules. This is sufficient to unblock Circe Native.
There was a boxing related bug when running the Cats tests, so no Native for that today. Scodec could also get Native in the future (bits is cross-published, but not core yet).
> Restore some Native builds

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/string.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/util/string.scala
- https://bugs.openjdk.org/browse/JDK-8295949
- https://github.com/openjdk/jdk/commit/4338f527aa81350e3636dcfbcd2eb17ddaad3914
> avoid deprecated `java.net.URL` constructor

- build.sbt
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/api/RefType.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/boolean.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/collection.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/ToInt.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/WitnessAs.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/numeric.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/package.scala
- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/types/string.scala
- modules/pureconfig/shared/src/test/scala/eu/timepit/refined/pureconfig/RefTypeConfigConvertSpec.scala
Fixes #1173 
This removes the shapeless dependency completely from the scala 3 version of each project. Where there was a natural replacement, I swapped it in:
- `shapeless.HNil` is now `scala.EmptyTuple`
- `shapeless.HList` is now `scala.Tuple`
- `shapeless.::` is now `scala.*:`
- `N <: shapeless.Nat` is now `N <: Int`
- `shapeless.nat._N` is now just `N`, taking advantage of literal types
- `shapeless.Succ` is now `scala.compiletime.ops.int.S`
- `shapeless.Witness.Aux` is now `scala.ValueOf`
There was no logical replacement for `shapeless.tag.@@`, so I removed code referencing it
> Remove shapeless dependency in scala 3

- .scalafmt.conf
- build.sbt
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/boolean.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/collection.scala
- modules/core/shared/src/main/scala/eu/timepit/refined/internal/Resources.scala
- Scala 3 report warnings since 3.4 https://github.com/lampepfl/dotty/pull/18813
- Scala 2.12 and 2.13 support new syntax without `-Xsource:3` option https://github.com/scala/scala/pull/10005
> enforce new wildcard syntax

- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/macros/RefineMacro.scala
for avoid [`eval`](https://github.com/fthomas/refined/blob/0683e875a829093e6c09b45e123143c91b821adb/modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/macros/RefineMacro.scala#L53)
> add `BigDecimal` and `BigInt` cache in `RefineMacro`

- .github/workflows/ci.yml
- build.sbt
- project/plugins.sbt
I noticed that Scala was updated to 3.4.1 (https://github.com/fthomas/refined/pull/1261) perhaps unintentionally - libraries in general are recommended to stay on LTS I believe, unless they use features only present in Scala Next.
> Update Scala Native to 0.5, revert to Scala 3.3

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/ToInt.scala
fix warning with Scala 3.5
```
[warn] -- [E197] Potential Issue Warning: modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/ToInt.scala:14:4 
[warn] 14 |    new ToInt[N] { override def apply(): Int = toInt[N] }
[warn]    |    ^
```
> use SAM instead of anonymous class

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/internal/WitnessAs.scala
There are already several specialized instances e.g. `intWitnessAsLong`. These should be higher priority than this generic instance that relies on `Numeric`.
Annoyingly, starting in Scala 3.6 the implicit resolution changes cause the following warning. Fixing the prioritization should address the warning.
```
[warn]    |Given search preference for eu.timepit.refined.internal.WitnessAs[(0 : Int), Long] between alternatives
[warn]    |  (eu.timepit.refined.internal.WitnessAs.intWitnessAsLong :
[warn]    |  [A <: Int]: eu.timepit.refined.internal.WitnessAs[A, Long])
[warn]    |and
[warn]    |  (eu.timepit.refined.internal.WitnessAs.intWitnessAs :
[warn]    |  [B, A <: Int]
[warn]    |    (implicit wa: ValueOf[A], ta: eu.timepit.refined.internal.ToInt[A], nb:
[warn]    |      Numeric[B]): …
```
> De-prioritize `intWitnessAs` implicit on Scala 3

- modules/core/shared/src/main/scala-3.0+/eu/timepit/refined/api/RefinedTypeOps.scala
- modules/core/shared/src/main/scala-3.0-/eu/timepit/refined/api/RefinedTypeOps.scala
avoid Intermediate `Either` objects
> optimize `RefinedTypeOps.unapply`
